export const SIGNUPUSER = "SIGNUPUSER";
export const SIGNUPUSER_SUCCESS = " SIGNUPUSER_SUCCESS";
export const SIGNUPUSER_FAIL = "SIGNUPUSER_FAIL";
export const SIGN_OUT = "SIGN_OUT";
export const SIGNUPLOGINSUCC = "SIGNUPLOGINSUCC";

export const REST_PASSWORD = "REST_PASSWORD";
export const REST_PASSWORD_FAIL = "REST_PASSWORD_FAIL";
export const REST_PASSWORD_SUCC = "REST_PASSWORD_SUCC";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGIN_USER = "LOGIN_USER";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const FETCH_PROFILE = "FETCH_PROFILE";

// Toggle Style
export const TOGGLE_STYLE = "TOGGLE_STYLE";

//Toggle Drawer
export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
